include "Types/Types.fbs";

namespace nos.audio;

enum BitDepth: uint
{
    AUDIO_BIT_DEPTH_24_BIT = 0
}

struct AudioPacketDescriptor
{
    sample_rate: uint;
    num_samples: uint;
    bit_depth: BitDepth;
    sample_stride: uint; // Number of bytes from one sample to another sample
    channel_count: uint; // Number of audio channels, each channel has its own sample in the packet and they are interleaved 
}

struct AudioPacket
{
    desc: AudioPacketDescriptor;
    buffer: nos.sys.vulkan.Buffer;
}